### ISSUE TITLE
readme needs screenshot / animated gif

### ISSUE THREAD

**Issue by szymonkaliski** [sdegutis/choose#2]
I can prepare one if you like?

**Comment by sdegutis** [comment]
Yes please! I had a `.mov` file but it was too big (file size), and I couldn't get it lower without the quality getting too low.

**Comment by sdegutis** [comment]
Figured out a way to do this using `screencapture`, `bash`, and `gifsicle`.

**Comment by sdegutis** [comment]
Oh and `sips`.

**Comment by sdegutis** [comment]
Done!
